version: "3.8"
services:
  funbox_merkushov_redis:
    image: redis:latest
    restart: always
    container_name: funbox_merkushov_redis
    networks:
      - funbox_merkushov_network

  funbox_merkushov_web:
    build:
      context: ../.
      dockerfile: devops/Dockerfile
    container_name: funbox_merkushov_web
    env_file: ../.env
#    command: tail -f /dev/null
    depends_on:
      - funbox_merkushov_redis
    volumes:
      - ./../:/opt/funbox
    ports:
      - "3000:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
    networks:
      - funbox_merkushov_network

networks:
  funbox_merkushov_network:
    driver: bridge